### ISSUE TITLE
TypeError: resnet50_projector() got an unexpected keyword argument 'weights'

### ISSUE THREAD

**Issue by PapaMadeleine2022** [OML-Team/open-metric-learning#332]
Hello, I change `configs/model/resnet.yaml` to:
```
name: resnet
args:
  arch: resnet50_projector
  gem_p: 5.0
  remove_fc: True
  normalise_features: False
  weights: resnet50_imagenet1k_v1

```
then train CUB dataset by `train_cub.py`, it shows error:

```
Your current logger is not able to log your files, you can use NeptuneLogger for this.
Error executing job with overrides: []
Traceback (most recent call last):
  File "train_cub.py", line 10, in main_hydra
    pl_train(cfg)
  File "/conda/envs/py3.7/lib/python3.7/site-packages/oml/lightning/entrypoints/train.py", line 82, in pl_train
    extractor = get_extractor_by_cfg(cfg["model"])
  File "/conda/envs/py3.7/lib/python3.7/site-packages/oml/registry/models.py", line 54, in get_extractor_by_cfg
    extractor = get_extractor(model_name=cfg["name"], **cfg["args"])
  File "/conda/envs/py3.7/lib/python3.7/site-packages/oml/registry/models.py", line 49, in get_extractor
    return _get_model(model_name=model_name, registry=EXTRACTORS_REGISTRY, **kwargs)
  File "/conda/envs/py3.7/lib/python3.7/site-packages/oml/registry/models.py", line 44, in _get_model
    model = registry[model_name](**kwargs)  # type: ignore
  File "/conda/envs/py3.7/lib/python3.7/site-packages/oml/models/resnet.py", line 121, in __init__
    state_dict = constructor(weights="IMAGENET1K_V1").state_dict()
TypeError: resnet50_projector() got an unexpected keyword argument 'weights'
```

How to fix it ? Looking forward to your reply.
Thanks very much~

**Comment by PapaMadeleine2022** [comment]
I get it. Thank you very much!
