### ISSUE TITLE
Support pytorch 2.0

### ISSUE THREAD

**Issue by cs-mshah** [OML-Team/open-metric-learning#395]
The dependencies for open-metric-learning aren't up to date. It would be great to have support for latest versions of various packages, especially `torch 2.0`

**Comment by cs-mshah** [comment]
I believe there are issues with versions. I created a new environment with python 3.9 and tried to install the library with `pip install -U open-metric-learning`. On successful installation I tried a few imports from the first lines of the example notebooks, but they threw errors:

```shell
>>> from oml.datasets.base import DatasetWithLabels
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/manan/anaconda3/envs/ncvprig/lib/python3.9/site-packages/oml/datasets/base.py", line 8, in <module>
    import torchvision
  File "/home/manan/anaconda3/envs/ncvprig/lib/python3.9/site-packages/torchvision/__init__.py", line 5, in <module>
    from torchvision import datasets, io, models, ops, transforms, utils
  File "/home/manan/anaconda3/envs/ncvprig/lib/python3.9/site-packages/torchvision/datasets/__init__.py", line 1, in <module>
    from ._optical_flow import FlyingChairs, FlyingThings3D, HD1K, KittiFlow, Sintel
  File "/home/manan/anaconda3/envs/ncvprig/lib/python3.9/site-packages/torchvision/datasets/_optical_flow.py", line 11, in <module>
    from ..io.image import _read_png_16
  File "/home/manan/anaconda3/envs/ncvprig/lib/python3.9/site-packages/torchvision/io/__init__.py", line 5, in <module>
    from ..utils import _log_api_usage_once
  File "/home/manan/anaconda3/envs/ncvprig/lib/python3.9/site-packages/torchvision/utils.py", line 23, in <module>
    @torch.no_grad()
AttributeError: module 'torch' has no attribute 'no_grad'
```

```shell
from oml.losses.triplet import TripletLossWithMiner
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/manan/anaconda3/envs/ncvprig/lib/python3.9/site-packages/oml/losses/triplet.py", line 4, in <module>
    from torch import Tensor
ImportError: cannot import name 'Tensor' from 'torch' (unknown location)
```

Is there some mistake in creating the environment? The colab notebook works fine.

**Comment by AlekseySh** [comment]
Hey, @cs-mshah , thank you for using OML!

I don't have this in my roadmap at the moment, but if you or anyone else could help with this, it would be great! Technically, it means to change torch version to 2.0 and make sure that all the tests work correctly.

**Comment by cs-mshah** [comment]
I'll try to work on this issue and other issues too.

**Comment by AlekseySh** [comment]
@cs-mshah you are welcome!!

**Comment by AlekseySh** [comment]
It's done!

**Comment by AlekseySh** [comment]
fyi @cs-mshah ^
