### ISSUE TITLE
How to use train model with ArcFace loss ?

### ISSUE THREAD

**Issue by PapaMadeleine2022** [OML-Team/open-metric-learning#496]
Hello, I want to train a model using `Classification ones`, like [ArcFace](https://open-metric-learning.readthedocs.io/en/latest/contents/losses.html#arcfaceloss). 
But how to use `train_inshop_arcface.yaml`? When I train model using [train_inshop.py](https://github.com/OML-Team/open-metric-learning/blob/main/pipelines/features_extraction/extractor_inshop/train_inshop.py) and `train_inshop_arcface.yaml`, it shows error:
```

...
  File "/workdir/anaconda3/envs/conda_py3.8/lib/python3.8/site-packages/oml/lightning/pipelines/train.py", line 82, in extractor_training_pipeline
    loader_train, loaders_val = get_retrieval_loaders(cfg)
  File "/workdir/anaconda3/envs/conda_py3.8/lib/python3.8/site-packages/oml/lightning/pipelines/train.py", line 38, in get_retrieval_loaders
    sampler = parse_sampler_from_config(cfg, train_dataset)
  File "/workdir/anaconda3/envs/conda_py3.8/lib/python3.8/site-packages/oml/lightning/pipelines/parser.py", line 153, in parse_sampler_from_config
    if (not dataset.categories_key) and cfg["sampler"]["name"] in SAMPLERS_CATEGORIES_BASED.keys():
TypeError: 'NoneType' object is not subscriptabl

```

**Comment by AlekseySh** [comment]
Hey, here is an [example](https://github.com/OML-Team/open-metric-learning/blob/main/tests/test_runs/test_pipelines/configs/train_arcface_with_categories.yaml) from CI/CD tests.
It works for `df_with_category.csv`, but I also checked that it works for a regular `df.csv`. Also tried to replace the sampler in the example by `null`. All combinations I tried worked.

So, please, check the difference between your config and the one from the example above.
If it doesn't fix the problem send me your full config.

I think the problem is that `sampler` is none for some reason. As a hotfix, you can pick any of our samplers from other examples.

**Comment by PapaMadeleine2022** [comment]
I use  the default `tests/test_runs/test_pipelines/configs/train.yaml` it works. But when I replace 
```
extractor:
  name: extractor_with_mlp
  args:
    mlp_features: [384]
    weights: null
    extractor:
      name: vit
      args:
        normalise_features: False
        use_multi_scale: False
        weights: null
        arch: vits16

scheduling:
  scheduler_interval: epoch
  scheduler_frequency: 1
  scheduler:
    name: multi_step
    args:
      milestones:
        - 1
        - 2
        - 3
```
to
```
extractor:
  name: vit_clip
  args:
    arch: vitb16_224
    weights: /xxx/pretrained/ViT-B-16.pt
    normalise_features: False

scheduling: null
```

But it shows error:

```
Your current logger is not able to log your files, you can use NeptuneLogger for this.
/workdir/anaconda3/envs/conda_py3.8/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py:20: LightningDeprecationWarning: The `pl.plugins.training_type.ddp.DDPPlugin` is deprecated in v1.6 and will be removed in v1.8. Use `pl.strategies.ddp.DDPStrategy` instead.
  rank_zero_deprecation(
/workdir/anaconda3/envs/conda_py3.8/lib/python3.8/site-packages/oml/datasets/base.py:303: DtypeWarning: Columns (4,5) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(dataset_root / dataframe_name, index_col=False)
/workdir/anaconda3/envs/conda_py3.8/lib/python3.8/site-packages/torch/serialization.py:779: UserWarning: 'torch.load' received a zip file that looks like a TorchScript archive dispatching to 'torch.jit.load' (call 'torch.jit.load' directly to silence this warning)
  warnings.warn("'torch.load' received a zip file that looks like a TorchScript archive"
Error executing job with overrides: []
Traceback (most recent call last):
  File "train.py", line 15, in main_hydra
    extractor_training_pipeline(cfg)
  File "/workdir/anaconda3/envs/conda_py3.8/lib/python3.8/site-packages/oml/lightning/pipelines/train.py", line 83, in extractor_training_pipeline
    extractor = get_extractor_by_cfg(cfg["extractor"])
  File "/workdir/anaconda3/envs/conda_py3.8/lib/python3.8/site-packages/oml/registry/models.py", line 54, in get_extractor_by_cfg
    extractor = get_extractor(model_name=cfg["name"], **cfg["args"])
  File "/workdir/anaconda3/envs/conda_py3.8/lib/python3.8/site-packages/oml/registry/models.py", line 49, in get_extractor
    return _get_model(model_name=model_name, registry=EXTRACTORS_REGISTRY, **kwargs)
  File "/workdir/anaconda3/envs/conda_py3.8/lib/python3.8/site-packages/oml/registry/models.py", line 44, in _get_model
    model = registry[model_name](**kwargs)  # type: ignore
  File "/workdir/anaconda3/envs/conda_py3.8/lib/python3.8/site-packages/oml/models/vit/clip.py", line 155, in __init__
    state_dict = state_dict.get("state_dict", state_dict)
  File "/workdir/anaconda3/envs/conda_py3.8/lib/python3.8/site-packages/torch/jit/_script.py", line 785, in __getattr__
    return super(RecursiveScriptModule, self).__getattr__(attr)
  File "/workdir/anaconda3/envs/conda_py3.8/lib/python3.8/site-packages/torch/jit/_script.py", line 502, in __getattr__
    return super(ScriptModule, self).__getattr__(attr)
  File "/workdir/anaconda3/envs/conda_py3.8/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1265, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'RecursiveScriptModule' object has no attribute 'get'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

That is weird.

**Comment by PapaMadeleine2022** [comment]
It seems to be the usage of `clip` which cause  the above problem. But how to fix it ?

**Comment by PapaMadeleine2022** [comment]
Another problem:
I train model using the following yaml:
```
postfix: metric_learning

seed: 42
precision: 32
accelerator: gpu
devices: [0,1,2,3]

dataframe_name: df_no_bboxes.csv
dataset_root: data/DeepFashion_InShop/
logs_root: logs/DeepFashion_InShop/
logs_folder: ${now:%Y-%m-%d_%H-%M-%S}_${postfix}

show_dataset_warnings: False

num_workers: 20
cache_size: 0

transforms_train:
  name: augs_hypvit_torch
  args:
    im_size: 224

transforms_val:
  name: norm_resize_hypvit_torch
  args:
    im_size: 224
    crop_size: 224

sampler:
  name: balance
  args:
    n_labels: 4
    n_instances: 4
bs_train: 256

bs_val: 128
max_epochs: 1000
valid_period: 1
  
metric_args:
  metrics_to_exclude_from_visualization: [cmc,]
  cmc_top_k: [1]
  map_top_k: [5]
  pfc_variance: [0.5, 0.9, 0.99]
  return_only_main_category: True
  visualize_only_main_category: True

log_images: True

metric_for_checkpointing: OVERALL/cmc/1

extractor:
  name: vit
  args:
    weights: /xxx/pretrained/dino_vitbase8_pretrain.pth
    normalise_features: False
    
criterion:
  name: arcface
  args:
    smoothing_epsilon: 0.0
    m: 0.4
    s: 64
    in_features: 768
    num_classes: 2623

optimizer:
  name: adam
  args:
    lr: 1e-5

# To use neptune you should also specify NEPTUNE_API_TOKEN in
# .env file or via `export NEPTUNE_API_TOKEN=...`
neptune_project: null


hydra_dir: ${logs_root}/${logs_folder}/

tags:
  - ${postfix}
  - deepfashion

hydra:
  run:
    dir: ${hydra_dir}
  searchpath:
   - pkg://oml.configs

``` 

The training is ok. But in the validating it show error:
```
Traceback (most recent call last):
  File "extractor_xxx/train_cub.py", line 10, in main_hydra
    extractor_training_pipeline(cfg)
  File "/workdir/yyy/metric-learning/open-metric-learning-release.0.4.0/oml/lightning/pipelines/train.py", line 142, in extractor_training_pipeline
    trainer.fit(model=pl_module)
  File "/workdir/anaconda3/envs/oml/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 770, in fit
    self._call_and_handle_interrupt(
  File "/workdir/anaconda3/envs/oml/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 721, in _call_and_handle_interrupt
    return self.strategy.launcher.launch(trainer_fn, *args, trainer=self, **kwargs)
  File "/workdir/anaconda3/envs/oml/lib/python3.8/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 93, in launch
    return function(*args, **kwargs)
  File "/workdir/anaconda3/envs/oml/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 811, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/workdir/anaconda3/envs/oml/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1236, in _run
    results = self._run_stage()
  File "/workdir/anaconda3/envs/oml/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1323, in _run_stage
    return self._run_train()
  File "/workdir/anaconda3/envs/oml/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1353, in _run_train
    self.fit_loop.run()
  File "/workdir/anaconda3/envs/oml/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 205, in run
    self.on_advance_end()
  File "/workdir/anaconda3/envs/oml/lib/python3.8/site-packages/pytorch_lightning/loops/fit_loop.py", line 294, in on_advance_end
    self.trainer._call_callback_hooks("on_train_epoch_end")
  File "/workdir/anaconda3/envs/oml/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1636, in _call_callback_hooks
    fn(self, self.lightning_module, *args, **kwargs)
  File "/workdir/anaconda3/envs/oml/lib/python3.8/site-packages/pytorch_lightning/callbacks/model_checkpoint.py", line 308, in on_train_epoch_end
    self._save_topk_checkpoint(trainer, monitor_candidates)
  File "/workdir/anaconda3/envs/oml/lib/python3.8/site-packages/pytorch_lightning/callbacks/model_checkpoint.py", line 377, in _save_topk_checkpoint
    raise MisconfigurationException(m)
pytorch_lightning.utilities.exceptions.MisconfigurationException: `ModelCheckpoint(monitor='OVERALL/cmc/1')` could not find the monitored key in the returned metrics: ['arcface_loss', 'arcface_loss_step', 'accuracy', 'arcface_loss_epoch', 'epoch', 'step']. HINT: Did you call `log('OVERALL/cmc/1', value)` in the `LightningModule`?
```

So many problems !

**Comment by PapaMadeleine2022** [comment]
need help~

**Comment by AlekseySh** [comment]
@PapaMadeleine2022 Sorry, I'm busy at the moment, but I'll take a look on Thursday or Friday.

**Comment by PapaMadeleine2022** [comment]
@AlekseySh

**Comment by AlekseySh** [comment]
Hey, @PapaMadeleine2022, sorry for the late response.

I think you are using the old version of OML.
For example, there are outdated params in your last config `return_only_main_category`, `visualize_only_main_category`. They named differently now. Moreover, there is no `arch` parameter in extractor, which is required.
**So, first of all, update OML.**

While working with the model you are going to use (I mean `vit_clip`) found a potential problem when we continue training from the weights stored on the disk. I fixed this here https://github.com/OML-Team/open-metric-learning/pull/500/files and will merge it soon. Except for this, the rest work fine for me.

So, try one more time on the latest OML, please.

**Comment by AlekseySh** [comment]
Hey, @PapaMadeleine2022, sorry for the late response.

I think you are using the old version of OML.
For example, there are outdated params in your last config: `return_only_main_category`, `visualize_only_main_category`. They named differently now. Moreover, there is no `arch` parameter in extractor, which is required.
So, first of all, update OML.

While working with the model you are going to use (I mean `vit_clip`) I found a potential problem when we continue training from the weights stored on the disk. I added the fix to the last OML release. After that that, the config similar to yours worked fine for me.

So, try one more time on the latest OML, please. If you have any problems, let me know and we will figure it out.

**Comment by AlekseySh** [comment]
due to inactivity
