### ISSUE TITLE
OML on Orange Pi 5 plus:  inference_on_images error with ddp init

### ISSUE THREAD

**Issue by yurikobyzev** [OML-Team/open-metric-learning#504]
Hello,

I am using my code on raspberry pi and jetson nano successfully, but when I try it on Orange Pi 5 plus, I got error,
something in is_ddp function ---  File "/home/lemon/open-metric-learning/oml/ddp/utils.py", line 77, in is_ddp
I'm not sure how to deal with this problem, can you help me?  Should i init_process_group  or make skip it in some way?

==================================================================================
Traceback (most recent call last):
  File "/home/lemon/netra/irisident/emb_dir.py", line 68, in <module>
    main()
  File "/home/lemon/netra/irisident/emb_dir.py", line 59, in main
    features_queries = inference_on_images(model, paths=imgpath, transform=transform, **args)
  File "/home/lemon/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/lemon/open-metric-learning/oml/inference/flat.py", line 37, in inference_on_images
    outputs = _inference(
  File "/home/lemon/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/lemon/open-metric-learning/oml/inference/abstract.py", line 32, in _inference
    if is_ddp():
  File "/home/lemon/open-metric-learning/oml/ddp/utils.py", line 77, in is_ddp
    get_world_size()
  File "/home/lemon/.local/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1555, in get_world_size
    return _get_group_size(group)
  File "/home/lemon/.local/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 836, in _get_group_size
    default_pg = _get_default_group()
  File "/home/lemon/.local/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 977, in _get_default_group
    raise ValueError(
ValueError: Default process group has not been initialized, please make sure to call init_process_group.
============================================================================================
lemon@lemon-desktop:~/netra/irisident$ uname -a
Linux lemon-desktop 5.10.160-rockchip #31 SMP Mon Feb 12 15:49:56 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux
===========================================================================================

**Comment by AlekseySh** [comment]
Hi, @yurikobyzev 

I had the same problem and figured out the the thing was in the requirements versions.
I've updated requirements and published it as a OML version.

So, you need to do two things:
- update your OML
- make sure that your torch and lightning are aligned with [reqs](https://github.com/OML-Team/open-metric-learning/blob/main/ci/requirements.txt) 

thank you for using OML!

**Comment by yurikobyzev** [comment]
Great! Thank you, now it works perfectly! :)

**Comment by AlekseySh** [comment]
@yurikobyzev thank you for using OML.

By the way, what did you do with OML on raspberry pi and jetson nano?

P.S. I would appreciate it if I could post the logo of your affiliation in the 'trusted by' section.
